### ISSUE TITLE
BoardResponseDto에 boardId가 실리지 않는 문제

### ISSUE THREAD

**Issue by 0chil** [swp2022/swp-server#15]
# 증상
<img width="330" alt="스크린샷 2022-05-19 08 05 25" src="https://user-images.githubusercontent.com/39221443/169169445-6c12c377-7399-42f7-8422-b6ea9c99c6af.png">

# 예상 원인
<img width="437" alt="스크린샷 2022-05-19 08 04 30" src="https://user-images.githubusercontent.com/39221443/169169347-ac647d64-9e86-400e-b6e8-b6ac752a5fb7.png">

@LEEYEONGJAE1 하나 빠뜨리셨네요😵

**Comment by LEEYEONGJAE1** [comment]
수정해서 leeyeongjae 브랜치에 push 했는데, 새로 pull request 파야 하면 알려주세요.

**Comment by 0chil** [comment]
@LEEYEONGJAE1 확실히 Issue는 잘 확인하기가 어렵군요. board작업을 하고 계시니 그대로 놔두도록 합시다
다음부터는 새로운 브랜치에서 해주세요
