### ISSUE TITLE
@PageableDefault와 Pageable 때문에 Presentation, Persistence가 결합하는 문제

### ISSUE THREAD

**Issue by LEEYEONGJAE1** [swp2022/swp-server#18]
이게 문제가 될 만한 상황이 떠오르지는 않는데, 해결할 방법이 떠오르시면 제시해주시면 감사하겠습니다.

**Comment by 0chil** [comment]
https://github.com/swp2022/swp-server/pull/14#discussion_r875967314

새 브랜치에서 해결하도록 합시다

**Comment by LEEYEONGJAE1** [comment]
넵.
