### ISSUE TITLE
없는 Endpoint 요청 시 GlobalExceptionHandler가 처리하지 않는 문제

### ISSUE THREAD

**Issue by 0chil** [swp2022/swp-server#5]
## 로그
<img width="355" alt="스크린샷 2022-05-11 21 59 08" src="https://user-images.githubusercontent.com/39221443/167855512-9c7c58ae-6138-47b0-b673-6700787675ae.png">
<img width="1047" alt="스크린샷 2022-05-11 22 00 49" src="https://user-images.githubusercontent.com/39221443/167855899-8f147f77-2272-41cc-ae60-f800324e6e9e.png">

## 상황
인증을 마치고 유효한 AccessToken을 이용해 
존재하지 않는 Endpoint에 요청할 시 Exception을 GlobalExceptionHandler에서 처리하지 않습니다.

## 관련 사례
[링크](https://velog.io/@shson/spring-rest-api%EC%97%90%EC%84%9C-not-found-exception%EC%B2%98%EB%A6%AC%ED%95%98%EA%B8%B0)

**Comment by sang-w0o** [comment]
404가 옳지 않다고 생각하시면 원하시는 처리되는 방식이 어떤건가요??

**Comment by 0chil** [comment]
@sang-w0o 404는 문제 없는데 , GlobalExceptionHandler가 이 상황에서 Exception Handling을 하지 못하고 있어 보입니다.

**Comment by sang-w0o** [comment]
> 인증을 마치고 유효한 AccessToken을 이용해
존재하지 않는 Endpoint에 요청할 시 Exception을 GlobalExceptionHandler에서 처리하지 않습니다.

404에 대해 발생하는 exception이 있나요??

**Comment by 0chil** [comment]
<img width="949" alt="스크린샷 2022-06-01 17 33 23" src="https://user-images.githubusercontent.com/39221443/171362717-df3ff859-4589-41ae-bfc5-d048ba4fa838.png">

`NotFoundException`을 통해서 `ErrorResponseDto` 로 반환되어야 할 것 같은데, 그렇지가 않네요.
코드 상으로는 GlobalExceptionHandler에서 잡혔다면, `500` 으로 반환될것 같이 보이는데, 그것도 아니구요.

**Comment by 0chil** [comment]
[이걸](https://stackoverflow.com/a/45785030) 찾았어요.
정리해보자면, Spring Boot은 기본적으로는 404를 직접 다루지 않고, @ControllerAdvice는 Controller의 범위에 국한 된 것 같네요.
따라서 애초부터 404를 다루는 Handler가 없으므로 기본 설정된 메시지가 나오는 것 같네요. @sang-w0o

**Comment by sang-w0o** [comment]
아 `ErrorResponseDto` 형태로 응답이 안나간다는 이야기였군요! 설정 해주고 싶다면 할 수 있겠지만 존재하지 않는 endpoint에 대해 404를 반환하는건 매우 일반적이기도 하고, 404의 응답 값으로 현재처럼 나가든, `ErrorResponseDto`로 나가든 클라이언트에서 처리하는 방식은 달라지지 않을 것 같아서 굳이 handling을 해줘야 하나 싶은 개인적인 의견이 있어요!

**Comment by 0chil** [comment]
@sang-w0o 저도 그 의견에는 동의합니다. 당연히 `ErrorResponseDto` 형태로 나갈 것 같은데, 나가지 않는 데 의문이 있었어요.
